// names-prophet.js
const namesProphet = [
  { arabic: "مُحَمَّد", translit: "Muhammad", urdu: "تعریف کیا گیا" },
  { arabic: "أَحْمَد", translit: "Ahmad", urdu: "سب سے زیادہ تعریف کیا گیا" },
  { arabic: "الْمُصْطَفَى", translit: "Al-Muṣṭafā", urdu: "منتخب کیا گیا" },
  { arabic: "الْمَاحِي", translit: "Al-Māḥi", urdu: "کفر کو مٹانے والا" },
  { arabic: "الْعَاقِب", translit: "Al-‘Āqib", urdu: "سب سے آخر میں آنے والا (نبی)" },
  { arabic: "الْمُزَّمِّل", translit: "Al-Muzzammil", urdu: "چادر اوڑھنے والا" },
  { arabic: "الْمُدَّثِّر", translit: "Al-Muddathir", urdu: "چادر لپیٹنے والا" },
  { arabic: "طٰهٰ", translit: "Ṭā Hā", urdu: "نبی اکرم ﷺ کا ایک اسم مبارک" },
  { arabic: "يٰسٓ", translit: "Yā Sīn", urdu: "قرآن میں ذکر کیا گیا اسم مبارک" },
  { arabic: "النَّبِيّ", translit: "An-Nabiyy", urdu: "نبی" },
  { arabic: "الرَّسُول", translit: "Ar-Rasūl", urdu: "رسول" },
  { arabic: "نَبِيُّ الرَّحْمَة", translit: "Nabiyy-ur-Raḥmah", urdu: "رحمت کے نبی" },
  { arabic: "نَبِيُّ التَّوْبَة", translit: "Nabiyy-ut-Tawbah", urdu: "توبہ کے نبی" },
  { arabic: "الْفَاتِح", translit: "Al-Fātiḥ", urdu: "کھولنے والا" },
  { arabic: "الْخَاتِم", translit: "Al-Khātim", urdu: "مہر لگانے والا (آخری نبی)" },
  { arabic: "الشَّافِع", translit: "Ash-Shāfi‘", urdu: "سفارش کرنے والا" },
  { arabic: "الْمُشَفَّع", translit: "Al-Mushaffa‘", urdu: "جس کی شفاعت قبول ہو" },
  { arabic: "رَؤُوف", translit: "Ra’ūf", urdu: "نہایت مہربان" },
  { arabic: "رَحِيم", translit: "Raḥīm", urdu: "نہایت رحم والا" },
  { arabic: "الْأُمِّي", translit: "Al-Ummiyy", urdu: "ناخواندہ (لیکن عالم کل)" },
  { arabic: "الصَّادِق", translit: "As-Ṣādiq", urdu: "سچ بولنے والا" },
  { arabic: "الْأَمِين", translit: "Al-Amīn", urdu: "امانت دار" },
  { arabic: "الْقَاسِم", translit: "Al-Qāsim", urdu: "تقسیم کرنے والا" },
  { arabic: "نَبِيُّ الْمَلْحَمَة", translit: "Nabiyy-ul-Malḥamah", urdu: "جنگ کے نبی" },
  { arabic: "نُور", translit: "Nūr", urdu: "روشنی" },
  { arabic: "السَّرَاجُ الْمُنِير", translit: "As-Sirāj-ul-Munīr", urdu: "روشن چراغ" },
  { arabic: "الْبَشِير", translit: "Al-Bashīr", urdu: "خوشخبری دینے والا" },
  { arabic: "النَّذِير", translit: "An-Nadhīr", urdu: "ڈرانے والا" },
  { arabic: "الدَّاعِي", translit: "Ad-Dā‘ī", urdu: "دعوت دینے والا" },
  { arabic: "السِّرَاج", translit: "As-Sirāj", urdu: "چراغ" },
  { arabic: "الْمُنِير", translit: "Al-Munīr", urdu: "روشن کرنے والا" },
  { arabic: "نَبِيُّ الْمَرْحَمَة", translit: "Nabiyy-ul-Marḥamah", urdu: "رحمت والے نبی" },
  { arabic: "الرَّسُولُ الْمُجْتَبَى", translit: "Ar-Rasūl-ul-Mujtabā", urdu: "منتخب کردہ رسول" },
  { arabic: "الْحَبِيب", translit: "Al-Ḥabīb", urdu: "محبوب" },
  { arabic: "نَبِيُّ الْهُدَى", translit: "Nabiyy-ul-Hudā", urdu: "ہدایت دینے والے نبی" },
  { arabic: "الْمُذَكِّر", translit: "Al-Mudhakkir", urdu: "یاد دلانے والا" },
  { arabic: "الْمُبَشِّر", translit: "Al-Mubashshir", urdu: "خوش خبری دینے والا" },
  { arabic: "الْمُنذِر", translit: "Al-Mundhir", urdu: "ڈرانے والا" },
  { arabic: "نَبِيُّ التَّقْوَى", translit: "Nabiyy-ut-Taqwā", urdu: "پرہیزگاری کے نبی" },
  { arabic: "نَبِيُّ الْمَغْفِرَة", translit: "Nabiyy-ul-Maghfirah", urdu: "مغفرت کے نبی" },
  { arabic: "الْهَادِي", translit: "Al-Hādī", urdu: "ہدایت دینے والا" },
  { arabic: "الشَّاهِد", translit: "Ash-Shāhid", urdu: "گواہ" },
  { arabic: "الْمُبِين", translit: "Al-Mubīn", urdu: "واضح کرنے والا" },
  { arabic: "الْمُعَلِّم", translit: "Al-Mu‘allim", urdu: "سکھانے والا" },
  { arabic: "الْمُبْلِغ", translit: "Al-Muballigh", urdu: "پہنچانے والا (پیغام)" },
  { arabic: "الرَّؤُوف الرَّحِيم", translit: "Ar-Ra’ūf ar-Raḥīm", urdu: "نہایت مہربان، رحم کرنے والا" },
  { arabic: "السَّلَام", translit: "As-Salām", urdu: "سلامتی دینے والا" },
  { arabic: "الصِّدِّيق", translit: "As-Ṣiddīq", urdu: "سچا دوست" },
  { arabic: "الرَّحْمَان", translit: "Ar-Raḥmān", urdu: "نہایت مہربان" },
  { arabic: "الصِّرَاط", translit: "As-Ṣirāṭ", urdu: "راہ راست" },
  { arabic: "الصِّفَة", translit: "As-Ṣifah", urdu: "اوصاف والا" },
  { arabic: "الزَّاهِد", translit: "Az-Zāhid", urdu: "زاہد (دنیا سے بے رغبت)" },
  { arabic: "الْخَلِيل", translit: "Al-Khalīl", urdu: "دوست" },
  { arabic: "الصَّفِي", translit: "Aṣ-Ṣafī", urdu: "چُنا ہوا" },
  { arabic: "الْمُؤَيَّد", translit: "Al-Mu'ayyad", urdu: "تائید یافتہ" },
  { arabic: "الْمُؤْتَمَن", translit: "Al-Mu’taman", urdu: "امانت دار" },
  { arabic: "السَّائِق", translit: "As-Sā’iq", urdu: "رہنمائی کرنے والا" },
  { arabic: "الْهَادِم", translit: "Al-Hādim", urdu: "باطل کو گرانے والا" },
  { arabic: "الْأَمِينُ الْمَأْمُون", translit: "Al-Amīn al-Ma’mūn", urdu: "ایمان دار و معتبر" },
  { arabic: "الْخَاتِمُ لِلنَّبِيِّين", translit: "Al-Khātim li-an-Nabiyyīn", urdu: "نبیوں کو ختم کرنے والا (آخری نبی)" },
  { arabic: "الْمُقَرَّب", translit: "Al-Muqarrab", urdu: "قریب کیا گیا" },
  { arabic: "الْمُتَوَكِّل", translit: "Al-Mutawakkil", urdu: "اللہ پر بھروسہ کرنے والا" },
  { arabic: "الْمُجَاهِد", translit: "Al-Mujāhid", urdu: "جہاد کرنے والا" },
  { arabic: "الْمُتَعَبِّد", translit: "Al-Muta‘abbid", urdu: "عبادت گزار" },
  { arabic: "الْأَفْصَح", translit: "Al-Afṣaḥ", urdu: "سب سے فصیح" },
  { arabic: "الْمُنْصِف", translit: "Al-Munṣif", urdu: "انصاف کرنے والا" },
  { arabic: "الْمُقْتَصِد", translit: "Al-Muqtasiḍ", urdu: "میانہ رو" },
  { arabic: "الزَّاكِي", translit: "Az-Zākī", urdu: "پاکیزہ" },
  { arabic: "الْخَلَائِق", translit: "Al-Khalā’iq", urdu: "مخلوق کے لیے رحمت" },
  { arabic: "الْمُكَرَّم", translit: "Al-Mukarram", urdu: "عزت والا" },
  { arabic: "الْأَكْرَم", translit: "Al-Akram", urdu: "سب سے زیادہ کرم کرنے والا" },
  { arabic: "الْبَرُّ الرَّحِيم", translit: "Al-Barr ar-Raḥīm", urdu: "نیکی و رحم والا" },
  { arabic: "الْمُؤْيَّدُ بِالرُّوحِ الْأَمِين", translit: "Al-Mu’ayyad bi-r-Rūḥ al-Amīn", urdu: "روح الامین سے تائید یافتہ" },
  { arabic: "الْمُطَاع", translit: "Al-Muṭā‘", urdu: "جس کی اطاعت کی جاتی ہے" },
  { arabic: "الْأَمْرُ", translit: "Al-Amr", urdu: "حکم دینے والا" },
  { arabic: "الْقَائِد", translit: "Al-Qā’id", urdu: "رہنما" },
  { arabic: "الزَّعِيم", translit: "Az-Za‘īm", urdu: "سربراہ" },
  { arabic: "الْمُخْلِص", translit: "Al-Mukhlis", urdu: "اخلاص والا" },
  { arabic: "الْغَالِب", translit: "Al-Ghālib", urdu: "غالب آنے والا" },
  { arabic: "الْقَارِئ", translit: "Al-Qāri’", urdu: "تلاوت کرنے والا" },
  { arabic: "الْمَفْتُوح لَهُ", translit: "Al-Maftūḥ lahu", urdu: "جس پر دروازے کھولے گئے" },
  { arabic: "الْمُقْتَفَى", translit: "Al-Muqtafā", urdu: "جس کی پیروی کی جائے" },
  { arabic: "الْمُقَدِّم", translit: "Al-Muqaddim", urdu: "آگے بڑھانے والا" },
  { arabic: "الْمُؤَسِّس", translit: "Al-Mu’assis", urdu: "بنیاد رکھنے والا" },
  { arabic: "الْمُبَارَك", translit: "Al-Mubārak", urdu: "برکت والا" },
  { arabic: "سَيِّد الْوَلِيِّين", translit: "Sayyid al-Waliyyīn", urdu: "ولیوں کا سردار" },
  { arabic: "سَيِّد الْمُرْسَلِينَ", translit: "Sayyid al-Mursalīn", urdu: "رسولوں کا سردار" },
  { arabic: "سَيِّد النَّاس", translit: "Sayyid an-Nās", urdu: "لوگوں کا سردار" },
  { arabic: "سَيِّد وَلَدِ آدَم", translit: "Sayyid Walad Ādam", urdu: "آدم کی اولاد کا سردار" },
  { arabic: "الْمُشَفَّع", translit: "Al-Mushaffa‘", urdu: "جس کی شفاعت قبول ہو" },
  { arabic: "الْمُحَامِي", translit: "Al-Muḥāmī", urdu: "دفاع کرنے والا" },
  { arabic: "الْمُطَاع فِي الْعَالَيْن", translit: "Al-Muṭā‘ fi-l-‘Ālayn", urdu: "اعلیٰ جماعت میں مطاع" },
  { arabic: "الْمُسْتَغْفِر لِلْمُؤْمِنِينَ", translit: "Al-Mustaghfir lil-Mu’minīn", urdu: "مومنوں کے لیے استغفار کرنے والا" },
  { arabic: "الرَّحْمَةُ الْمُهْدَاة", translit: "Ar-Raḥmat-ul-Muhdāh", urdu: "بطور رحمت بھیجا گیا" },
  { arabic: "الْمُتَكَلِّم بِالوَحْي", translit: "Al-Mutakallim bi-l-Waḥy", urdu: "وحی کے ذریعے بات کرنے والا" },
  { arabic: "الْحَسَنُ الْخُلُق", translit: "Al-Ḥasan-ul-Khuluq", urdu: "اچھے اخلاق والا" },
  { arabic: "سَيِّد الْمُتَّقِينَ", translit: "Sayyid al-Muttaqīn", urdu: "متقیوں کا سردار" },
  { arabic: "الْمُكَرَّم بِالوَحْي", translit: "Al-Mukarram bi-l-Waḥy", urdu: "وحی سے عزت دیا گیا" },
  { arabic: "الْمُكَرَّم بِالشَّفَاعَة", translit: "Al-Mukarram bi-sh-Shafā‘ah", urdu: "شفاعت سے معزز" },
  { arabic: "الْمُجْتَبَى", translit: "Al-Mujtabā", urdu: "چُنا گیا" },
  { arabic: "الْمُسْتَفْتَح", translit: "Al-Mustaf’taḥ", urdu: "جس پر دروازے کھولے جائیں" },
  { arabic: "الْمُؤَيَّد بِجِبْرِيل", translit: "Al-Mu’ayyad bi-Jibrīl", urdu: "جبرائیل سے تائید یافتہ" },
  { arabic: "الْمَرْحُوم", translit: "Al-Marḥūm", urdu: "جس پر رحم کیا گیا" },
  { arabic: "الرَّسُول الْمَسْكُون", translit: "Ar-Rasūl al-Maskūn", urdu: "اطمینان والا رسول" }
];
